name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: ppc_investment
          POSTGRES_USER: dbadmin
          POSTGRES_PASSWORD: RNNToken2024
        options: > 
          --health-cmd="pg_isready -U dbadmin" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    steps:
    - uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: pgsql

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Update environment variables
      run: |
        sed -i 's/DB_CONNECTION=.*/DB_CONNECTION=pgsql/' .env
        sed -i 's/DB_HOST=.*/DB_HOST=127.0.0.1/' .env
        sed -i 's/DB_PORT=.*/DB_PORT=5432/' .env
        sed -i 's/DB_DATABASE=.*/DB_DATABASE=ppc_investment/' .env
        sed -i 's/DB_USERNAME=.*/DB_USERNAME=dbadmin/' .env
        sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=RNNToken2024/' .env

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Run migrations
      run: php artisan migrate --force

    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      run: php artisan test
